nodeLinker: node-modules

# Enable legacy peer deps for compatibility with @atlaskit packages
npmRegistryServer: "https://registry.npmjs.org"

# Improve installation performance
enableGlobalCache: true

# Package manager settings
preferInteractive: true

# Development settings
enableImmutableInstalls: false